server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.237.128:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: 192.168.237.128
    port: 6379

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
